stages:
 - test
 - scan
 - build
 - publish

variables:
  SONAR_SCANNER_VERSION: 5.0.1.3006

test_job:
  stage: test
  tags:
    - linux
  script:
    - sudo apt-get update
    - sudo rm -rf /var/lib/dpkg/lock-frontend /var/lib/dpkg/lock /var/cache/debconf/*.dat /var/cache/apt/archives/lock
    - sudo dpkg --configure -a
    - sudo apt-get install -f
    - sudo apt-get install -y python3-dev python3-pip
    - sh testscript.sh
  artifacts:
    paths:
      - src/coverage.xml
  variables:
    GIT_STRATEGY: clone

scan_job:
  stage: scan
  tags:
    - linux
  script:
    - sudo apt-get update
    - sudo rm -rf /var/lib/dpkg/lock-frontend /var/lib/dpkg/lock /var/cache/debconf/*.dat /var/cache/apt/archives/lock
    - sudo dpkg --configure -a
    - sudo apt-get install -f
    - sudo apt-get install -y unzip default-jre
    - pushd ~
    - curl -o /tmp/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_SCANNER_VERSION}.zip
    - unzip -n /tmp/sonar-scanner.zip
    - popd
    - ~/sonar-scanner-${SONAR_SCANNER_VERSION}/bin/sonar-scanner
  dependencies:
    - test_job
  artifacts:
    paths:
      - src/coverage.xml
  variables:
    GIT_STRATEGY: clone

build:
  stage: build
  tags:
    - linux
  script:
    - sudo apt-get update
    - sudo rm -rf /var/lib/dpkg/lock-frontend /var/lib/dpkg/lock /var/cache/debconf/*.dat /var/cache/apt/archives/lock
    - sudo dpkg --configure -a
    - sudo apt-get install -f
    - sudo apt-get install -y python3-dev python3-pip
    - pip3 install -r requirements.txt
    - cd src
    - python3 setup.py sdist bdist_wheel
  artifacts:
    paths:
      - src/dist/*.tar.gz
      - src/dist/*.whl

publish:
  stage: publish
  tags:
    - linux
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - export DEBCONF_NONINTERACTIVE_SEEN=true
    - echo 'keyboard-configuration keyboard-configuration/layoutcode select us' | sudo debconf-set-selections
    - echo 'keyboard-configuration keyboard-configuration/modelcode select pc105' | sudo debconf-set-selections
    - echo 'keyboard-configuration keyboard-configuration/variant select English (US)' | sudo debconf-set-selections
    - echo 'keyboard-configuration keyboard-configuration/optionscode string compose:ralt' | sudo debconf-set-selections
    - echo 'keyboard-configuration keyboard-configuration/unsupported_layout boolean true' | sudo debconf-set-selections
    - echo 'keyboard-configuration keyboard-configuration/unsupported_config_layout boolean true' | sudo debconf-set-selections
    - sudo apt-get update
    - sudo apt-get install -y keyboard-configuration
    - sudo dpkg-reconfigure --frontend=noninteractive keyboard-configuration
    - sudo apt-get install -y python3-dev python3-pip
    - pip install twine
    - ~/.local/bin/twine upload --repository-url https://nexus.ellisbs.co.uk/repository/pypi-hosted/ --username $PYPI_USERNAME --password $PYPI_PASSWORD src/dist/*
  artifacts:
    paths:
      - src/dist/*.tar.gz
      - src/dist/*.whl
  dependencies:
    - build

